# Generated by Django 4.2.2 on 2023-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.image'),
        ),
    ]
