# Generated by Django 4.2.2 on 2023-07-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_image_galleries'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='galleries',
            field=models.ManyToManyField(to='core.gallery'),
        ),
    ]
